version: 2.1
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          name: restore-yarn-pkg-cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-package
          command: yarn install --frozen-lockfile
      - save_cache:
          name: save-yarn-pkg-cache
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn run build
      - run:
          name: firebase-deploy
          command: firebase deploy --token "$FIREBASE_TOKEN" --only hosting
