version: 2.1
jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-package
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: yarn build
      - run:
        name: firebase-deploy
        command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting
